// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  theSidebar: [
    'intro',
    {
      type: 'category', 
      label: 'Access Web3 APIs ⚡️',
      collapsible: false,
      link: {
        type: 'generated-index'
      },
      items: [
        {
          type: 'autogenerated', 
          dirName: 'access-apis'
        },        
      ]
    },
    {
      type: 'category', 
      label: 'Power-up Lava 🌋',
      collapsible: false,
      link: {
        type: 'doc',
        id: 'power-lava-intro'
      },
      items: [
        {
          type: 'category', 
          label: 'Be a Validator',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'validator'
          },
          items: [
            {
              type: 'autogenerated', 
              dirName: 'validator'
            },        
          ]
        },    
        'provider'
      ]
    },
    {
      type: 'category', 
      label: 'Lava Network',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Lava Blockchain'
      },
      items: [
        'lava-blockchain/hardware-requirements',
        {
          type: 'category', 
          label: 'Join Testnet',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'lava-blockchain/join-testnet'
          },
          items: [
            'lava-blockchain/join-testnet-manual',        
          ]
        },
        'lava-blockchain/faucet',
        'lava-blockchain/account-wallet'
      ]
    },
    'faq',
    {
      type: 'link',
      label: 'Contribution',
      href: 'https://github.com/lavanet/docs/blob/master/CONTRIBUTING.md',
    },
  ],
};

module.exports = sidebars;