export const communityMainnetEndpointsList = [
  {
    provider: 'ndnodes',
    service: '🌐 RPC',
    url: 'https://rpc.lava-mainnet.ndnodes.com',
    notes: 'Archive Node',
  },
  {
    provider: 'ndnodes',
    service: '🔗 REST API',
    url: 'https://api.lava-mainnet.ndnodes.com',
    notes: 'Archive Node',
  },
  {
    provider: 'Pathrock Network',
    service: '🌐 RPC',
    url: 'https://rpc.lava.pathrocknetwork.org',
    notes: '',
  },
  {
    provider: 'Pathrock Network',
    service: '🔗 REST API',
    url: 'https://api.lava.pathrocknetwork.org',
    notes: '',
  },
  {
    provider: 'Pathrock Network',
    service: '⚡ gRPC',
    url: 'grpc.lava.pathrocknetwork.org',
    notes: '',
  },
  {
    provider: 'BlockPro',
    service: '🔗 REST API',
    url: 'https://lava-api.block-pro.net',
    notes: 'Pruned Node',
  },
  {
    provider: 'BlockPro',
    service: '🌐 RPC',
    url: 'https://lava-rpc.block-pro.net',
    notes: 'Pruned Node',
  },
  {
    provider: '0Base VC',
    service: '🌐 RPC',
    url: 'https://lava-rpc.0base.dev:443',
    notes: 'Pruned Node',
  },
  {
    provider: '0Base VC',
    service: '🔗 REST API',
    url: 'https://lava-rest.0base.dev',
    notes: 'Pruned Node',
  },
  {
    provider: 'Nodefleet',
    service: '⚡ gRPC',
    url: 'grpc.lava-mainnet.nodefleet.org:443',
    notes: 'Archive Node',
  },
  {
    provider: 'Nodefleet',
    service: '🔗 REST API',
    url: 'https://rest.lava-mainnet.nodefleet.org',
    notes: 'Archive Node',
  },
  {
    provider: 'Nodefleet',
    service: '🌐 RPC',
    url: 'https://tendermint.lava-mainnet.nodefleet.org',
    notes: 'Archive Node',
  },
  {
    provider: 'Bware Labs',
    service: '🔗 REST API',
    url: 'https://lava-mainnet-archive-lcd.bwarelabs.com',
    notes: 'Archive Node',
  },
  {
    provider: 'Bware Labs',
    service: '🌐 RPC',
    url: 'https://lava-mainnet-archive-rpc.bwarelabs.com',
    notes: 'Archive Node',
  },
  {
    provider: '5elements Nodes',
    service: '🌐 RPC',
    url: 'https://rpclight-lava.5elementsnodes.com',
    notes: 'Pruned Node',
  },
  {
    provider: '5elements Nodes',
    service: '🌐 RPC',
    url: 'https://rpc-lava.5elementsnodes.com',
    notes: 'Archive Node',
  },
  {
    provider: 'Impulse Expert',
    service: '🌐 RPC',
    url: 'https://m-rpc.lava.eu01.impulse.expert',
    notes: 'Archive Node',
  },
  {
    provider: 'Impulse Expert',
    service: '🔗 REST API',
    url: 'https://m-api.lava.eu01.impulse.expert',
    notes: 'Archive Node',
  },
  {
    provider: 'Impulse Expert',
    service: '⚡ gRPC',
    url: 'm-grpc.eu01.lava.impulse.expert',
    notes: 'Archive Node',
  },
  {
    provider: 'Impulse Expert',
    service: '🌐 RPC',
    url: 'https://m-rpc.lava.us01.impulse.expert',
    notes: 'Pruned Node',
  },
  {
    provider: 'Impulse Expert',
    service: '🔗 REST API',
    url: 'https://m-api.lava.us01.impulse.expert',
    notes: 'Pruned Node',
  },
  {
    provider: 'Impulse Expert',
    service: '⚡ gRPC',
    url: 'm-grpc.lava.us01.impulse.expert',
    notes: 'Pruned Node',
  },
  {
    provider: 'Cosmos Spaces',
    service: '🌐 RPC',
    url: 'https://rpc-lava.cosmos-spaces.cloud',
    notes: 'Pruned Node',
  },
  {
    provider: 'Cosmos Spaces',
    service: '🔗 REST API',
    url: 'https://api-lava.cosmos-spaces.cloud',
    notes: 'Pruned Node',
  },
  {
    provider: 'Cosmos Spaces',
    service: '⚡ gRPC',
    url: 'grpc-lava.cosmos-spaces.cloud:443',
    notes: 'Pruned Node',
  },
  {
    provider: 'Cosmos Spaces',
    service: '🌐 RPC',
    url: 'https://rpc-lava-archive.cosmos-spaces.cloud',
    notes: 'Archive Node',
  },
  {
    provider: 'Cosmos Spaces',
    service: '🔗 REST API',
    url: 'https://api-lava-archive.cosmos-spaces.cloud',
    notes: 'Archive Node',
  },
  {
    provider: 'Cosmos Spaces',
    service: '⚡ gRPC',
    url: 'grpc-lava-archive.cosmos-spaces.cloud:443',
    notes: 'Archive Node',
  },
  {
    provider: 'Node101',
    service: '⚡ gRPC',
    url: 'https://mainnet-grpc-lava.rpc101.org',
    notes: '',
  },
  {
    provider: 'Node101',
    service: '🌐 RPC',
    url: 'https://mainnet-lava.rpc101.org',
    notes: '',
  },
  {
    provider: 'Node101',
    service: '🌐 RPC',
    url: 'https://mainnet-lcd-lava.rpc101.org',
    notes: 'Pruned Node',
  },
  {
    provider: 'Node101',
    service: '🔗 Web API',
    url: 'https://mainnet-webapi-lava.rpc101.org',
    notes: '',
  },
  {
    provider: 'StakeVillage',
    service: '🌐 RPC',
    url: 'https://lava.rpc.stakevillage.net:443',
    notes: 'Archive Node',
  },
  {
    provider: 'StakeVillage',
    service: '🌐 RPC',
    url: 'https://lava.arc-rpc.stakevillage.net:443',
    notes: 'Archive Node',
  },
  {
    provider: 'StakeVillage',
    service: '🔗 REST API',
    url: 'https://lava.api.stakevillage.net',
    notes: 'Pruned Node',
  },
  {
    provider: 'StakeVillage',
    service: '⚡ gRPC',
    url: 'lava.grpc.stakevillage.net:443',
    notes: 'Pruned Node',
  },
  {
    provider: 'CryptoSJnet',
    service: '🌐 RPC',
    url: 'https://lavamainnetarchiverpc.cryptosj.net',
    notes: 'Archive Node',
  },
  {
    provider: 'CryptoSJnet',
    service: '🔗 REST API',
    url: 'https://lavamainnetarchiveapi.cryptosj.net',
    notes: 'Archive Node',
  },
  {
    provider: 'AviaOne',
    service: '🌐 RPC',
    url: 'https://rpc.lava-mainnet-1.lava.aviaone.com',
    notes: 'Pruned Node',
  },
  {
    provider: 'AviaOne',
    service: '🔗 REST API',
    url: 'https://api.lava-mainnet-1.lava.aviaone.com',
    notes: 'Pruned Node',
  },
  {
    provider: 'AviaOne',
    service: '⚡ gRPC',
    url: 'grpc.lava-mainnet-1.lava.aviaone.com:9092',
    notes: 'Pruned Node',
  },
  {
    provider: 'Chainbase',
    service: '🌐 RPC',
    url: 'https://lava-rpc-mainnet.s.chainbase.online',
    notes: 'Pruned Node',
  },
  {
    provider: 'itrocket',
    service: '🌐 RPC',
    url: 'https://lava-mainnet-rpc.itrocket.net:443',
    notes: 'Archive Node, 15 calls/sec per IP',
  },
  {
    provider: 'itrocket',
    service: '🔗 REST API',
    url: 'https://lava-mainnet-api.itrocket.net:443',
    notes: 'Archive Node',
  },
  {
    provider: 'itrocket',
    service: '⚡ gRPC',
    url: 'lava-mainnet-grpc.itrocket.net:443',
    notes: 'Archive Node',
  },
  {
    provider: 'MH Ventures',
    service: '🌐 RPC',
    url: 'https://lava.mhventures.io',
    notes: 'Archive Node',
  },
  {
    provider: 'Data Nexus',
    service: '🌐 RPC',
    url: 'https://mainnet-archive.lavanet.datanexus.tech/',
    notes: 'Archive Node',
  },
  {
    provider: 'Data Nexus',
    service: '⚡ gRPC',
    url: 'https://grpc.mainnet-archive.lavanet.datanexus.tech/',
    notes: 'Archive Node',
  },
  {
    provider: 'Data Nexus',
    service: '🔗 REST API',
    url: 'https://lcd.mainnet-archive.lavanet.datanexus.tech/',
    notes: 'Archive Node',
  },
  {
    provider: 'kokos',
    service: '🌐 RPC',
    url: 'https://rpc-archive-lava.sbgid.com',
    notes: 'Archive Node',
  },
  {
    provider: 'kokos',
    service: '🔗 REST API',
    url: 'https://api-lava.sbgid.com',
    notes: 'Archive Node',
  },
];
