export const communityMainnetEndpointsList = [
  {
    provider: 'ndnodes',
    service: '🌐 RPC',
    url: 'https://rpc.lava-mainnet.ndnodes.com/',
    notes: '',
  },
  {
    provider: 'ndnodes',
    service: '🔗 API',
    url: 'https://api.lava-mainnet.ndnodes.com/',
    notes: '',
  },
  {
    provider: 'Pathrock Network',
    service: '🌐 RPC',
    url: 'https://rpc.lava.pathrocknetwork.org/',
    notes: '',
  },
  {
    provider: 'Pathrock Network',
    service: '🔗 API',
    url: 'https://api.lava.pathrocknetwork.org/',
    notes: '',
  },
  {
    provider: 'Pathrock Network',
    service: '⚡ gRPC',
    url: 'grpc.lava.pathrocknetwork.org',
    notes: '',
  },
  {
    provider: 'BlockPro',
    service: '🔗 API',
    url: 'https://lava-api.block-pro.net/',
    notes: '',
  },
  {
    provider: 'BlockPro',
    service: '🌐 RPC',
    url: 'https://lava-rpc.block-pro.net/',
    notes: '',
  },
  {
    provider: '0Base VC',
    service: '🌐 RPC',
    url: 'https://lava-rpc.0base.dev:443',
    notes: '',
  },
  {
    provider: '0Base VC',
    service: '🔗 API',
    url: 'https://lava-rest.0base.dev',
    notes: '',
  },
  {
    provider: 'Nodefleet',
    service: '⚡ gRPC',
    url: 'grpc.lava-mainnet.nodefleet.org:443',
    notes: 'Lava mainnet archival node',
  },
  {
    provider: 'Nodefleet',
    service: '🔗 REST',
    url: 'https://rest.lava-mainnet.nodefleet.org',
    notes: 'Lava mainnet archival node',
  },
  {
    provider: 'Nodefleet',
    service: '🌐 RPC',
    url: 'https://tendermint.lava-mainnet.nodefleet.org',
    notes: 'Lava mainnet archival node',
  },
  {
    provider: 'Bware Labs',
    service: '📦 Archive LCD',
    url: 'https://lava-mainnet-archive-lcd.bwarelabs.com/',
    notes: '',
  },
  {
    provider: 'Bware Labs',
    service: '📦 Archive RPC',
    url: 'https://lava-mainnet-archive-rpc.bwarelabs.com/',
    notes: '',
  },
  {
    provider: '5elements Nodes',
    service: '🌐 Pruned RPC',
    url: 'https://rpclight-lava.5elementsnodes.com/',
    notes: '',
  },
  {
    provider: '5elements Nodes',
    service: '📦 Archive RPC',
    url: 'https://rpc-lava.5elementsnodes.com/',
    notes: '',
  },
  {
    provider: 'Impulse Expert',
    service: '📦 Archive RPC',
    url: 'https://m-rpc.lava.eu01.impulse.expert',
    notes: 'Lava mainnet archival node',
  },
  {
    provider: 'Impulse Expert',
    service: '📦 Archive API',
    url: 'https://m-api.lava.eu01.impulse.expert',
    notes: 'Lava mainnet archival node',
  },
  {
    provider: 'Impulse Expert',
    service: '📦 Archive gRPC',
    url: 'm-grpc.eu01.lava.impulse.expert',
    notes: 'Lava mainnet archival node',
  },
  {
    provider: 'Impulse Expert',
    service: '🌐 RPC',
    url: 'https://m-rpc.lava.us01.impulse.expert',
    notes: '',
  },
  {
    provider: 'Impulse Expert',
    service: '🔗 API',
    url: 'https://m-api.lava.us01.impulse.expert',
    notes: '',
  },
  {
    provider: 'Impulse Expert',
    service: '⚡ gRPC',
    url: 'm-grpc.lava.us01.impulse.expert',
    notes: '',
  },
  {
    provider: 'Cosmos Spaces',
    service: '🌐 Pruned RPC',
    url: 'https://rpc-lava.cosmos-spaces.cloud',
    notes: '',
  },
  {
    provider: 'Cosmos Spaces',
    service: '🔗 Pruned API',
    url: 'https://api-lava.cosmos-spaces.cloud',
    notes: '',
  },
  {
    provider: 'Cosmos Spaces',
    service: '⚡ Pruned GRPC',
    url: 'grpc-lava.cosmos-spaces.cloud:443',
    notes: '',
  },
  {
    provider: 'Cosmos Spaces',
    service: '📦 Archive RPC',
    url: 'https://rpc-lava-archive.cosmos-spaces.cloud',
    notes: '',
  },
  {
    provider: 'Cosmos Spaces',
    service: '📦 Archive API',
    url: 'https://api-lava-archive.cosmos-spaces.cloud',
    notes: '',
  },
  {
    provider: 'Cosmos Spaces',
    service: '⚡ Archive GRPC',
    url: 'grpc-lava-archive.cosmos-spaces.cloud:443',
    notes: '',
  },
  {
    provider: 'Node101',
    service: '⚡ gRPC',
    url: 'https://mainnet-grpc-lava.rpc101.org',
    notes: '',
  },
  {
    provider: 'Node101',
    service: '🌐 RPC',
    url: 'https://mainnet-lava.rpc101.org/',
    notes: '',
  },
  {
    provider: 'Node101',
    service: '🛤️ LCD',
    url: 'https://mainnet-lcd-lava.rpc101.org',
    notes: '',
  },
  {
    provider: 'Node101',
    service: '🔗 Web API',
    url: 'https://mainnet-webapi-lava.rpc101.org',
    notes: '',
  },
  {
    provider: 'StakeVillage',
    service: '🌐 RPC',
    url: 'https://lava.rpc.stakevillage.net:443',
    notes: '',
  },
  {
    provider: 'StakeVillage',
    service: '📦 Archive RPC',
    url: 'https://lava.arc-rpc.stakevillage.net:443',
    notes: '',
  },
  {
    provider: 'StakeVillage',
    service: '🔗 API',
    url: 'https://lava.api.stakevillage.net',
    notes: '',
  },
  {
    provider: 'StakeVillage',
    service: '⚡ GRPC',
    url: 'lava.grpc.stakevillage.net:443',
    notes: '',
  },
  {
    provider: 'CryptoSJnet',
    service: '📦 Archive RPC',
    url: 'https://lavamainnetarchiverpc.cryptosj.net',
    notes: '',
  },
  {
    provider: 'CryptoSJnet',
    service: '📦 Archive API',
    url: 'https://lavamainnetarchiveapi.cryptosj.net',
    notes: '',
  },
  {
    provider: 'AviaOne',
    service: '🌐 RPC',
    url: 'https://rpc.lava-mainnet-1.lava.aviaone.com',
    notes: 'State Sync required',
  },
  {
    provider: 'AviaOne',
    service: '🔗 API',
    url: 'https://api.lava-mainnet-1.lava.aviaone.com',
    notes: 'For explorer and other services',
  },
  {
    provider: 'AviaOne',
    service: '⚡ GRPC',
    url: 'grpc.lava-mainnet-1.lava.aviaone.com:9092',
    notes: '',
  },
  {
    provider: 'Chainbase',
    service: '🌐 RPC',
    url: 'https://lava-rpc-mainnet.s.chainbase.online',
    notes: '',
  },
  {
    provider: 'itrocket',
    service: '📦 Archive RPC',
    url: 'https://lava-mainnet-rpc.itrocket.net:443',
    notes: '15 calls/sec per IP',
  },
  {
    provider: 'itrocket',
    service: '🔗 API',
    url: 'https://lava-mainnet-api.itrocket.net:443',
    notes: '',
  },
  {
    provider: 'itrocket',
    service: '⚡ GRPC',
    url: 'lava-mainnet-grpc.itrocket.net:443',
    notes: '',
  },
  {
    provider: 'MH Ventures',
    service: '🌐 RPC',
    url: 'https://lava.mhventures.io',
    notes: '',
  },
];
